version: "3.9"
services:
  wdc-tanstack-starter-kit-db:
    image: postgres
    restart: always
    container_name: wdc-tanstack-starter-kit-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

  s3-bucket:
    build: .
    restart: always
    ports:
      - 9000:9000
    command: "node s3.mjs"
    environment:
      AWS_ACCESS_KEY_ID: S3RVER
      AWS_SECRET_ACCESS_KEY: S3RVER
    volumes:
      - ".:/home/app"

volumes:
  postgres:
